# Generated by Django 4.1.6 on 2023-02-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField()),
                ('view', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('sqft_living', models.FloatField()),
                ('bathrooms', models.FloatField()),
                ('waterfront', models.IntegerField()),
                ('sqft_above', models.IntegerField()),
                ('sqft_basement', models.IntegerField()),
                ('sqft_living15', models.IntegerField()),
                ('days_since', models.IntegerField()),
                ('predicted_price', models.FloatField(null=True)),
            ],
        ),
    ]
