# Generated by Django 4.1.6 on 2023-02-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseprice',
            old_name='days_since',
            new_name='days_since_reference_date',
        ),
    ]
