# Generated by Django 4.1.6 on 2023-02-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_rename_days_since_houseprice_days_since_reference_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=10)),
                ('view', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('sqft_living', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('waterfront', models.IntegerField()),
                ('sqft_above', models.IntegerField()),
                ('sqft_basement', models.IntegerField()),
                ('sqft_living15', models.IntegerField()),
                ('days_since_reference_date', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HousePrice',
        ),
    ]
